#!/bin/ash

# INFLUXDB

service influxdb restart

sleep 3;
influx  << EOF
CREATE DATABASE IF NOT EXISTS $INFLUXDB_DB;
CREATE USER "$INFLUXDB_ADMIN_USER"@"%" IDENTIFIED BY "$INFLUXDB_ADMIN_PASS";
GRANT ALL PRIVILEGES ON $INFLUXDB_DB.* TO "$INFLUXDB_ADMIN_USER"@"%" WITH GRANT OPTION;
CREATE USER "$INFLUXDB_USER"@"%" IDENTIFIED BY "$INFLUXDB_PASS";
GRANT ALL PRIVILEGES ON $INFLUXDB_DB.* TO "$INFLUXDB_USER"@"%" WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF

tail -f /dev/null
