#!/bin/ash

# INFLUXDB

service influxdb restart

sleep 3;
influx  << EOF
CREATE DATABASE $INFLUXDB_DB;
CREATE USER "$INFLUXDB_ADMIN_USER" WITH PASSWORD "$INFLUXDB_ADMIN_PASS" WITH ALL
PRIVILEGES;
CREATE USER "$INFLUXDB_USER" WITH PASSWORD "$INFLUXDB_PASS";
GRANT ALL ON "$INFLUXDB_DB" TO "$INFLUXDB_USER";
FLUSH PRIVILEGES;
EOF
#GRANT ALL PRIVILEGES ON $INFLUXDB_DB.* TO "$INFLUXDB_ADMIN_USER"@"%" WITH ALL PRIVILEGES;

tail -f /dev/null
