#!/bin/ash

# INFLUXDB

service influxdb restart
#influxd -config /etc/influxdb.conf

sleep 5;
influx  << EOF
CREATE USER "$INFLUXDB_ADMIN_USER" WITH PASSWORD "$INFLUXDB_ADMIN_PASS" WITH ALL
PRIVILEGES;
CREATE DATABASE "$INFLUXDB_DB";
CREATE USER "$INFLUXDB_USER" WITH PASSWORD "$INFLUXDB_PASS";
EOF

#influx << EOF
#SHOW DATABASES;
#SHOW USERS;
#EOF

tail -f /dev/null
