apiVersion: v1
kind: Service
metadata:
  annotations:
        metallb.universe.tf/allow-shared-ip: shared
        metallb.universe.tf/address-pool: ip-pools
  name: phpmyadmin
spec:
  selector:
      app: phpmyadmin
  type: LoadBalancer
  ports:
      -   name: http
          protocol: TCP
          port: 5000
          targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: my-phpmyadmin
        name: phpmyadmin
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - ./livenessprobe.sh
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - name: http
          containerPort: 5000