apiVersion: v1
kind: Service
metadata:
  annotations:
        metallb.universe.tf/allow-shared-ip: shared
        metallb.universe.tf/address-pool: ip-pools
  name: wordpress
spec:
  ports:
  - name: http
    protocol: TCP
    port: 5050  
    targetPort: 5050
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: my-wordpress
        imagePullPolicy: Never
        env:
          # Use secret in real usage
        - name: DB_NAME
          value: $DB_NAME
        - name: DB_USER
          value: $DB_USER
        - name: DB_PASS
          value: $DB_PASS
        - name: MYSQL_IP
          value: $MYSQL_IP
        ports:
        - name: http
          containerPort: 5050
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"