apiVersion: v1
kind: Service
metadata:
  annotations:
        metallb.universe.tf/allow-shared-ip: shared
        metallb.universe.tf/address-pool: ip-pools
  name: wordpress
spec:
    selector:
        app: wordpress
    type: LoadBalancer
    ports:
        -   name: http
            protocol: TCP
            port: 5050
            targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: my-wordpress
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - ./livenessprobe.sh
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: DB_NAME
          value: wp_db
        - name: DB_USER
          value: user
        - name: DB_PASS
          value: user
        - name: MYSQL_IP
          value: mysql
        ports:
        - name: http
          containerPort: 5050
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"