apiVersion: v1
kind: Service
metadata:
  annotations:
        metallb.universe.tf/allow-shared-ip: shared
        metallb.universe.tf/address-pool: ip-pools
  name: telegraf
spec:
    selector:
        app: telegraf
    type: LoadBalancer
    ports:
        -   name: http
            protocol: TCP
            port: 8125
            targetPort: 8125
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: my-telegraf
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8125
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
