apiVersion: v1
kind: Service
metadata:
  annotations:
        metallb.universe.tf/allow-shared-ip: shared
        metallb.universe.tf/address-pool: ip-pools
  name: telegraf
spec:
    selector:
        app: telegraf
    type: ClusterIP
    ports:
        -   name: http
            protocol: TCP
            port: 8125
            targetPort: 8125
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: my-telegraf
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - ./livenessprobe.sh
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - name: http
          containerPort: 8125
        volumeMounts:
          - name: telegraf-endpoint
            mountPath: "/var/run/docker.sock"
      volumes:
      - name: telegraf-endpoint
        hostPath:
          path: /var/run/docker.sock
