
apiVersion: v1
kind: Service
metadata:
  annotations:
        metallb.universe.tf/allow-shared-ip: shared
        metallb.universe.tf/address-pool: ip-pools
  name: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - name: ftps-20
    port: 20
    targetPort: 20
  - name: ftps-21
    port: 21
    targetPort: 21
  - name: ftps-21000
    port: 21000
    targetPort: 21000
  - name: ftps-21001
    port: 21001
    targetPort: 21001
  - name: ftps-21002
    port: 21002
    targetPort: 21002
  - name: ftps-21003
    port: 21003
    targetPort: 21003
  - name: ftps-21004
    port: 21004
    targetPort: 21004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my-ftps
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - ./livenessprobe.sh
          initialDelaySeconds: 10
          periodSeconds: 10
        # env:
        #   - name: FTPS_USER
        #     value: user
        #   - name: FTPS_PASS
        #     value: user
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004